# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vSimulatorWrap <- function(arrayStates, arrayErrors, arrayF, arrayW, arrayG, modelLags) {
    .Call('_legion_vSimulatorWrap', PACKAGE = 'legion', arrayStates, arrayErrors, arrayF, arrayW, arrayG, modelLags)
}

vFitterWrap <- function(yt, matvt, matF, matw, matG, modellags, Etype, Ttype, Stype, ot) {
    .Call('_legion_vFitterWrap', PACKAGE = 'legion', yt, matvt, matF, matw, matG, modellags, Etype, Ttype, Stype, ot)
}

vForecasterWrap <- function(matvt, matF, matw, series, h, Etype, Ttype, Stype, modellags) {
    .Call('_legion_vForecasterWrap', PACKAGE = 'legion', matvt, matF, matw, series, h, Etype, Ttype, Stype, modellags)
}

vOptimiserWrap <- function(yt, matvt, matF, matw, matG, modellags, Etype, Ttype, Stype, cfType, normalizer, bounds, ot, otObs) {
    .Call('_legion_vOptimiserWrap', PACKAGE = 'legion', yt, matvt, matF, matw, matG, modellags, Etype, Ttype, Stype, cfType, normalizer, bounds, ot, otObs)
}

