# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vSimulatorWrap <- function(arrayStates, arrayErrors, arrayF, arrayW, arrayG, modelLags) {
    .Call('_legion_vSimulatorWrap', PACKAGE = 'legion', arrayStates, arrayErrors, arrayF, arrayW, arrayG, modelLags)
}

discounter <- function(matrixF, matrixW, matrixG, k) {
    .Call('_legion_discounter', PACKAGE = 'legion', matrixF, matrixW, matrixG, k)
}

vFitterWrap <- function(matrixY, matrixV, matrixF, matrixW, matrixG, lags, E, T, S, matrixO, backcast) {
    .Call('_legion_vFitterWrap', PACKAGE = 'legion', matrixY, matrixV, matrixF, matrixW, matrixG, lags, E, T, S, matrixO, backcast)
}

vForecasterWrap <- function(matrixV, matrixF, matrixW, nSeries, hor, E, T, S, lags) {
    .Call('_legion_vForecasterWrap', PACKAGE = 'legion', matrixV, matrixF, matrixW, nSeries, hor, E, T, S, lags)
}

